import Navbar from "@/components/Navbar";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import axios from "axios"
import Link from "next/link";
import Pageli from "@/components/Pageli";
import { useSession } from "next-auth/react"
import NavbarPage from "@/components/NavbarPage";

export default function notebook() {
    const { data: session } = useSession()

    const router = useRouter();
    const nid = router.query.nid;
    const [notebook, setNotebook] = useState({})
    const [pages, setPages] = useState([])
    const [title, setTitle] = useState("")
    useEffect(() => {
        async function get() {
            const data = await axios.get(`/api/pagefuncs/getNbByPageId/${nid}`)
            setNotebook(data.data.notebook)
            setTitle(data.data.notebook.name)
            const res2 = await axios.get(`/api/notebookfuncs/getPagesByNotebook/${nid}`)
            setPages(res2.data.pages)
            
        }
        get()
        
    }, [nid])
    

    const updateTitle = async(e) => {
        e.preventDefault();
        await axios.post("/api/notebookfuncs/editTitle", {
            nid: notebook.id,
            title: title
        })
    }
    return (
        <>
        <Head>
        <title>Notebook - Notelite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>

      </Head>
      <main>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>       
      {notebook && (<NavbarPage uemail={notebook.uemail} nbid={notebook.id} nbname={notebook.name}/>)}<br/>
      <div class="container" style={{maxWidth: 1000}}>
          {notebook && (
            <>
            <input className="form-control" value={title} placeholder="Change title" onChange={(e) => setTitle(e.target.value)}></input>
            <hr/>
            <button className="btn btn-dark" onClick={updateTitle}>Save</button>
                </>
            )}
            
           
      </div>
      </main>
        </>
    )
}