import Navbar from '@/components/Navbar'
import Head from 'next/head'
import { useSession, signIn, signOut } from "next-auth/react"
import { useEffect, useState } from 'react';
import NotebookLi from '@/components/NotebookLi';
import axios from "axios"

export default function Home() {
  const { data: session } = useSession();
  const [notebooks, setNotebooks] = useState([])
  useEffect(() => {
    async function getNotebooks() {
      const data = await axios.get("/api/notebookfuncs/getNotebooks")
      console.log(data.data)
      setNotebooks(data.data.data)

    }
    getNotebooks()
  }, [notebooks])
  return (
    <>
      <Head>
        <title>Notelite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>

      </Head>
      <main>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>       
 <Navbar/><br/>
      <div class="container">
        {session && (
          <>
          
        <h5>Howdy, {session.user.name}</h5>
        <br/>
          </>
        )}
        
        {session && (
          <>
        {notebooks.map(notebook => 
          <NotebookLi title={notebook.name} descr={notebook.description} uemail={notebook.uemail}/>
        )}
        </>
        )}
        {!session && (
          <>
          <h3>Take notes, use notes, and store notes all on Notelite</h3>
          </>
        )}
      </div>
      </main>
    </>
  )
}
