import Navbar from "@/components/Navbar";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import axios from "axios"

export default function id() {
    const router = useRouter();
    const nid = router.query.nid;
    const [notebook, setNotebook] = useState()
    
    
    useEffect(() => {
        const data = axios.post(`/api/notebookfuncs/getNotebook`, {
            nid: nid,
    
           
        }).then(function (response) {
            setNotebook(response.data.notebook)
        }).catch(function (error) {
        });
    }, notebook)
    return (
        <>
        <Head>
        <title>Notebook - Notelite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"/>

      </Head>
      <main>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>       
      <Navbar/><br/>
      <div class="container" style={{maxWidth: 1100}}>
          {notebook && (
            <>
            <nav class="navbar navbar-light" style={{borderBottom: "1px solid lightgray"}}>
            <a class="navbar-brand">
            {notebook.name}
            </a>
            <form class="form-inline">
                <button className="btn btn-primary">+ New page</button>
            </form>
            </nav>

            </>
          )}
        
      </div>
      </main>
        </>
    )
}